title: Add Person 
name: Add Person
description: Add a new person to the people section 
title: "Add a new member"
labels: ["enhancement"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to add new information to our site!
  - type: input
    id: first_name
    attributes:
      label: First Name
      description: 
      placeholder: ex. Jon
    validations:
      required: true
  - type: input
    id: last_name
    attributes:
      label: Last Name
      description: 
      placeholder: ex. Doe
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Title
      description: 
      placeholder: ex. Dr
    validations:
      required: false
  - type: input
    id: position
    attributes:
      label: Position
      description: 
      placeholder: Professor of ...
    validations:
      required: false
  - type: input
    id: role
    attributes:
      label: Role
      description: 
      placeholder: ex. Director of ...
    validations:
      required: false
  - type: input
    id: email
    attributes:
      label: Email
      description: 
      placeholder:
    validations:
      required: true
  - type: input
    id: web
    attributes:
      label: Web
      description: 
      placeholder:
    validations:
      required: false
  - type: input
    id: scholar
    attributes:
      label: Scholar
      description: 
      placeholder: Google Scholar
    validations:
      required: false
  - type: input
    id: orcid
    attributes:
      label: Orcid
      description: 
      placeholder: Orcid ID
    validations:
      required: false