title: Add Person 
name: Add Person
description: Add a new person to the [people section](https://intelligentsystemslaboratory.github.io/bristol-ai/people/) 
title: "Add a new member"
labels: ["enhancement"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to add new information to our site!
  - type: input
    id: id
    attributes:
      label: ID
      description: Your University of Bristol ID 
      placeholder: e.g. Jon
    validations:
      required: true 
  - type: input
    id: first_name
    attributes:
      label: First Name
      description: 
      placeholder: e.g. Jon
    validations:
      required: true
  - type: input
    id: last_name
    attributes:
      label: Last Name
      description: 
      placeholder: e.g. Doe
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Title
      description: 
      placeholder: e.g. Dr, Prof, ...
    validations:
      required: false
  - type: input
    id: position
    attributes:
      label: Position
      description: 
      placeholder: Professor of ...
    validations:
      required: false
  - type: input
    id: role
    attributes:
      label: Role
      description: 
      placeholder: e.g. Director of ...
    validations:
      required: false
  - type: input
    id: email
    attributes:
      label: Email
      description: 
      placeholder:
    validations:
      required: true
  - type: input
    id: web
    attributes:
      label: Web
      description: URL to your personal website or a webpage with information about you
      placeholder:
    validations:
      required: false
  - type: input
    id: scholar
    attributes:
      label: Google Scholar user ID
      description: This can be obtained from your Google Scholar URL after the parameter `?user=`
      placeholder: e.g. o9ggd4sAAAAJ
    validations:
      required: false
  - type: input
    id: orcid
    attributes:
      label: Orcid ID
      description: This is formed by 16 alphanumeric characters divided into 4 blocks of 4
      placeholder: e.g. 0000-0001-6857-5810
    validations:
      required: false