name: Write Form Information

on:
  issues:
    types:
      - opened

jobs:
  write-form-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run script to write form information
        run: |
          issueNumber=${{ github.event.issue.number }}
          issueBody="${{ github.event.issue.body }}"
          targetFile="_data/output.yml"
          id=$(echo "$body" | awk '/### ID/{getline; print}' | tr -d '[:space:]')
          first_name=$(echo "$body" | awk '/### First Name/{getline; print}' | tr -d '[:space:]')
          last_name=$(echo "$body" | awk '/### Last Name/{getline; print}' | tr -d '[:space:]')
          email=$(echo "$body" | awk '/### Email/{getline; print}' | tr -d '[:space:]')

          echo "Body: $issueBody"
          echo "ID: $id_value"
          echo "First Name: $first_name_value"
          echo "Last Name: $last_name_value"
          echo "Email: $email_value"

          yamlContent=$(cat <<EOF
          title: "Add Person"
          info :"Info"
          body: |
            ${issueBody}
            ID: ${id}
          EOF
          ) 
          echo "$yamlContent" > "$targetFile"

      - name: Commit and push changes
        run: |
          git config --global user.email "daladiersampaio@gmail.com"
          git config --global user.name "DelmiroDaladier"
          git add "_data/output.yml"
          git commit -m "Auto-commit changes"
          git push origin gh-pages