name: Write Form Information

on:
  issues:
    types:
      - opened

jobs:
  write-form-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run script to write form information
        run: |
          issueNumber=${{ github.event.issue.number }}
          issueBody="${{ github.event.issue.body }}"
          
          if [[ "${issueBody}" == *"Add"* ]]; then
            targetFile="_data/people.yml"
          else [[ "${issueBody}" == *"ADD Group"* ]]; then
            targetFile="_data/groups.yml"
          fi
          
          targetFile="_data/people.yml"

          echo "${issueBody}"

          echo -e "\n" >> "$targetFile"
          echo "- ${issueBody}" | sed '2,$s/^/  /' >> "$targetFile"

      - name: Commit and push changes
        run: |
          git config --global user.email "daladiersampaio@gmail.com"
          git config --global user.name "DelmiroDaladier"
          git add "_data/people.yml"
          git commit -m "Auto-commit changes"
          git push origin gh-pages
