name: Write Form Information

on:
  issues:
    types:
      - opened

jobs:
  write-form-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run script to write form information
        run: |
          issueNumber=${{ github.event.issue.number }}
          issueBody="${{ github.event.issue.body }}"
          targetFile="_data/output_${issueNumber}.yml"
          
          yamlContent=$(cat <<EOF
          title: "Add Person"
          info :"Info"
          body: |
            ${issueBody}
          EOF
          ) 
          echo "$yamlContent" > "$targetFile"

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add "$targetFile"
          git commit -m "Add form information for issue ${{ github.event.issue.number }}"
          git push
